/**
 * Authorisation (SEC-010, SEC-011, ZT-001).
 *
 * Every route must declare its required capability. The `onRoute` hook below
 * throws at registration time when a route omits the declaration, so a route
 * without an authorisation decision cannot reach a running server — the
 * "absence of a declaration fails the build" requirement, enforced by the
 * framework rather than by review.
 *
 * The declaration is only half of it. Capability answers "may this role do this
 * at all"; entity scope answers "may it do it *here*". Handlers that touch a
 * specific entity call `requireReadEntity` / `requireWriteEntity`, which
 * re-derive scope from the session (SEC-011).
 */

import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import {
  can,
  canReadEntity,
  canWriteEntity,
  isPrivileged,
  requiresStepUp,
  type Capability,
  type Principal,
} from '@spendifre/shared';
import type { AppConfig } from '../config.ts';
import type { Db } from '../db/pool.ts';
import { forbidden, notFound, stepUpRequired, unauthenticated } from './errors.ts';
import { authorisationDenials } from '../observability/metrics.ts';
import { isSameOrigin } from './security.ts';
import { isAuthFresh, loadSession, sessionCookieName, touchSession, verifyCsrf } from '../auth/session.ts';

export type RouteSecurity =
  /** Deliberately unauthenticated: sign-in start, callback, health, CSP report. */
  | { readonly mode: 'public' }
  /** Any authenticated principal; the handler performs its own scoping. */
  | { readonly mode: 'authenticated' }
  /** A named capability from the SPEC §5 matrix. */
  | { readonly mode: 'capability'; readonly capability: Capability };

declare module 'fastify' {
  interface FastifyRequest {
    principal: Principal | null;
    sessionToken: string | null;
    displayName: string | null;
  }
  interface FastifyContextConfig {
    security?: RouteSecurity;
  }
}

const STATE_CHANGING = new Set(['POST', 'PUT', 'PATCH', 'DELETE']);

export function registerRouteDeclarationCheck(app: FastifyInstance): void {
  app.addHook('onRoute', (routeOptions) => {
    // HEAD is auto-generated by Fastify from GET and inherits its config.
    if (routeOptions.method === 'HEAD') return;
    const security = routeOptions.config?.security;
    if (!security) {
      throw new Error(
        `route ${String(routeOptions.method)} ${routeOptions.url} has no security declaration ` +
          '(SEC-010: every endpoint declares its required role and entity scope)',
      );
    }
  });
}

export function registerAuthGuard(app: FastifyInstance, db: Db, config: AppConfig): void {
  app.decorateRequest('principal', null);
  app.decorateRequest('sessionToken', null);
  app.decorateRequest('displayName', null);

  app.addHook('preHandler', async (request: FastifyRequest, _reply: FastifyReply) => {
    const security = request.routeOptions.config?.security;
    if (!security) {
      // An unmatched URL has no route options at all; that is a 404, not a
      // missing declaration, so it falls through to the not-found handler.
      if (!request.routeOptions.url) return;
      // A matched route without a declaration cannot happen — onRoute refuses
      // to register one — but failing closed here means a future change to
      // that hook cannot open a hole silently.
      throw forbidden('missing security declaration at request time');
    }

    const cookieName = sessionCookieName(config.cookieSecure);
    const token = request.cookies[cookieName] ?? null;
    if (token) {
      const session = await loadSession(db, token, config);
      if (session) {
        request.sessionToken = token;
        request.displayName = session.displayName;
        request.principal = {
          userId: session.userId,
          role: session.role,
          ownedEntityIds: session.ownedEntityIds,
        };

        // ZT-002 / ZT-003: privileged roles require a compliant device and a
        // phishing-resistant authentication method. If Conditional Access did
        // not deliver both, the session is treated as unauthenticated rather
        // than quietly downgraded.
        if (isPrivileged(session.role)) {
          const strongAuth = session.amr.some((m) =>
            ['mfa', 'fido', 'hwk', 'phr', 'phrh'].includes(m),
          );
          if (!strongAuth || !session.deviceCompliant) {
            request.principal = null;
            throw unauthenticated('privileged role without compliant device or strong auth');
          }
        }

        if (STATE_CHANGING.has(request.method)) {
          if (!isSameOrigin(request, config.PUBLIC_ORIGIN)) {
            authorisationDenials({ reason: 'cross_origin' });
            throw forbidden('cross-origin state-changing request');
          }
          const presented = request.headers['x-csrf-token'];
          if (!verifyCsrf(session, typeof presented === 'string' ? presented : undefined)) {
            authorisationDenials({ reason: 'csrf' });
            throw forbidden('missing or invalid CSRF token');
          }
        }

        if (security.mode === 'capability' && requiresStepUp(security.capability)) {
          if (!isAuthFresh(session, config.STEP_UP_MAX_AGE_MINUTES)) {
            authorisationDenials({ reason: 'step_up' });
            throw stepUpRequired('primary authentication is too old for this action');
          }
        }

        await touchSession(db, token);
      }
    }

    if (security.mode === 'public') return;

    if (!request.principal) throw unauthenticated('no valid session');

    if (security.mode === 'capability' && !can(request.principal.role, security.capability)) {
      // ZT-008: clustered denials are the shape of someone probing endpoints.
      // The *capability* is labelled, never the actor — a metrics store is not
      // covered by SEC-011.
      authorisationDenials({ reason: 'capability', capability: security.capability });
      throw forbidden(`role ${request.principal.role} lacks ${security.capability}`);
    }
  });
}

export function principalOf(request: FastifyRequest): Principal {
  if (!request.principal) throw unauthenticated('handler requires a principal');
  return request.principal;
}

/**
 * SEC-011 on a read path. Out-of-scope resolves to 404, so comparing status
 * codes tells an attacker nothing about which identifiers exist.
 */
export function requireReadEntity(request: FastifyRequest, entityId: string): Principal {
  const principal = principalOf(request);
  if (!canReadEntity(principal, entityId)) throw notFound('entity out of read scope');
  return principal;
}

/**
 * SEC-011 on a write path. 403, because naming the object is already proof the
 * caller knows it exists.
 */
export function requireWriteEntity(request: FastifyRequest, entityId: string): Principal {
  const principal = principalOf(request);
  if (!canWriteEntity(principal, entityId)) throw forbidden('entity out of write scope');
  return principal;
}

/** Convenience for declaring a route's security inline at registration. */
export const publicRoute = { security: { mode: 'public' } as const };
export const authenticatedRoute = { security: { mode: 'authenticated' } as const };
export const requires = (capability: Capability) => ({
  security: { mode: 'capability', capability } as const,
});
